#!/bin/bash

function createuser() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/user.insurance.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/user.insurance.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-user --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy user's CA cert to user's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/tlscacerts/ca.crt"

  # Copy user's CA cert to user's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.insurance.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.insurance.com/tlsca/tlsca.user.insurance.com-cert.pem"

  # Copy user's CA cert to user's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.insurance.com/ca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.insurance.com/ca/ca.user.insurance.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-user --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-user --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-user --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-user --id.name useradmin --id.secret useradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls" --enrollment.profile tls --csr.hosts peer0.user.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer0.user.insurance.com/tls/server.key"

  echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls" --enrollment.profile tls --csr.hosts peer1.user.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/user.insurance.com/peers/peer1.user.insurance.com/tls/server.key"


  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/users/User1@user.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.insurance.com/users/User1@user.insurance.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://useradmin:useradminpw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.insurance.com/users/Admin@user.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.insurance.com/users/Admin@user.insurance.com/msp/config.yaml"
}

function createinCompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/inCompany.insurance.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/inCompany.insurance.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-inCompany --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-inCompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-inCompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-inCompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-inCompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy inCompany's CA cert to inCompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/tlscacerts/ca.crt"

  # Copy inCompany's CA cert to inCompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/tlsca/tlsca.inCompany.insurance.com-cert.pem"

  # Copy inCompany's CA cert to inCompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/ca"
  cp "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/ca/ca.inCompany.insurance.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-inCompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-inCompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-inCompany --id.name inCompanyadmin --id.secret inCompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-inCompany -M "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-inCompany -M "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls" --enrollment.profile tls --csr.hosts peer0.inCompany.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/peers/peer0.inCompany.insurance.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-inCompany -M "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/users/User1@inCompany.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/users/User1@inCompany.insurance.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://inCompanyadmin:inCompanyadminpw@localhost:8054 --caname ca-inCompany -M "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/users/Admin@inCompany.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/inCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/inCompany.insurance.com/users/Admin@inCompany.insurance.com/msp/config.yaml"
}

function creategovAgency() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/govAgency.insurance.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/govAgency.insurance.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-govAgency --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy govAgency's CA cert to govAgency's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/tlscacerts/ca.crt"

  # Copy govAgency's CA cert to govAgency's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/tlsca/tlsca.govAgency.insurance.com-cert.pem"

  # Copy govAgency's CA cert to govAgency's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/ca"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/ca/ca.govAgency.insurance.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name govAgencyadmin --id.secret govAgencyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls" --enrollment.profile tls --csr.hosts peer0.govAgency.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/peers/peer0.govAgency.insurance.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/users/User1@govAgency.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/users/User1@govAgency.insurance.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://govAgencyadmin:govAgencyadminpw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/users/Admin@govAgency.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.insurance.com/users/Admin@govAgency.insurance.com/msp/config.yaml"
}

function createreInsurer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/reInsurer.insurance.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-reInsurer --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-reInsurer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-reInsurer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-reInsurer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-reInsurer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy reInsurer's CA cert to reInsurer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/tlscacerts/ca.crt"

  # Copy reInsurer's CA cert to reInsurer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/tlsca/tlsca.reInsurer.insurance.com-cert.pem"

  # Copy reInsurer's CA cert to reInsurer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/ca"
  cp "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/ca/ca.reInsurer.insurance.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-reInsurer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-reInsurer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-reInsurer --id.name reInsureradmin --id.secret reInsureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-reInsurer -M "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-reInsurer -M "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls" --enrollment.profile tls --csr.hosts peer0.reInsurer.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/peers/peer0.reInsurer.insurance.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-reInsurer -M "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/users/User1@reInsurer.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/users/User1@reInsurer.insurance.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://reInsureradmin:reInsureradminpw@localhost:10054 --caname ca-reInsurer -M "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/users/Admin@reInsurer.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reInsurer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reInsurer.insurance.com/users/Admin@reInsurer.insurance.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/insurance.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/insurance.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/insurance.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/insurance.com/msp/tlscacerts/tlsca.insurance.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/insurance.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/insurance.com/tlsca/tlsca.insurance.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/insurance.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls" --enrollment.profile tls --csr.hosts orderer.insurance.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/msp/tlscacerts/tlsca.insurance.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/insurance.com/users/Admin@insurance.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/insurance.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/insurance.com/users/Admin@insurance.com/msp/config.yaml"
}



createuser
createinCompany
creategovAgency
createreInsurer
createOrderer
