Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/insurance.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.insurance.com:7050
  - &user
    Name: userMSP
    ID: userMSP
    MSPDir: ../organizations/peerOrganizations/user.insurance.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('userMSP.admin', 'userMSP.peer', 'userMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('userMSP.admin', 'userMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('userMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('userMSP.peer')"
  - &inCompany
    Name: inCompanyMSP
    ID: inCompanyMSP
    MSPDir: ../organizations/peerOrganizations/inCompany.insurance.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('inCompanyMSP.admin', 'inCompanyMSP.peer', 'inCompanyMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('inCompanyMSP.admin', 'inCompanyMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('inCompanyMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('inCompanyMSP.peer')"

  - &govAgency
    Name: govAgencyMSP

    ID: govAgencyMSP

    MSPDir: ../organizations/peerOrganizations/govAgency.insurance.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('govAgencyMSP.admin', 'govAgencyMSP.peer', 'govAgencyMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('govAgencyMSP.admin', 'govAgencyMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('govAgencyMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('govAgencyMSP.peer')" 

  - &reInsurer
    Name: reInsurerMSP
    ID: reInsurerMSP
    MSPDir: ../organizations/peerOrganizations/reInsurer.insurance.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('reInsurerMSP.admin', 'reInsurerMSP.peer', 'reInsurerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('reInsurerMSP.admin', 'reInsurerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('reInsurerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('reInsurerMSP.peer')"



Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.insurance.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.insurance.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *user
        - *inCompany
        - *govAgency
        - *reInsurer
      Capabilities: *ApplicationCapabilities
